// <auto-generated/>
using System.Runtime.CompilerServices;

// ReSharper disable once CheckNamespace
namespace Cake.MicrosoftTeams
{
    /// <summary>
    /// This namespace contains Microsoft Teams aliases.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }
}