//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.MicrosoftTeams")]
[assembly: AssemblyDescription("Cake Microsoft Teams AddIn")]
[assembly: AssemblyCompany("WCOM AB")]
[assembly: AssemblyProduct("Cake.MicrosoftTeams")]
[assembly: AssemblyVersion("0.3.0")]
[assembly: AssemblyFileVersion("0.3.0")]
[assembly: AssemblyInformationalVersion("0.3.0")]
[assembly: AssemblyCopyright("Copyright © WCOM AB 2016")]
[assembly: CLSCompliant(true)]
